config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "homes#top"
  get '/about' => 'homes#about'
  resources :books
  resources :users, only: [:show,:edit,:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :books, dependent: :destroy
has_one_attached :image
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path
  end
  
 def after_sign_out_path_for(resource)
    about_path
 end

  
protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end

  def index
    @books = Book.all
    
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])

  end

  def show
    
  end
  
  def index
    @users = User.all 
  end
  
  private
  def user
    params.require(:user).permit(:name,:introduction, :image )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <tr>
    <th>Title</th> <th>Opinion</th> 
  </tr>
 <% @books.each do |book| %>
<div>
  <tr>
    <td><%= link_to book_path(book.id) do %>
    <%= book.title %> <% end %></td>
    <td><%= book.body %></td>
  </tr>
</div>
<% end %> 
</table>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h1>Book detail</h1>

<div>
<p><%= @book.title %></p>
<p><%= @book.body %></p>
<p><%= @book.user_id %></p>
</div>

app/views/homes/about.html.erb
<h1>about</h1>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
    <% if user_signed_in? %>
    
      <li>
        <%= link_to '投稿フォーム', new_book_path %>
      </li>
      <li>
      <%= link_to 'マイページ', users_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_with model: @user do |f| %>
<label for="inputName">Name</label>
<%= f.text_field :name, autofocus: true, id:"inputName",placeholder:"Name" %>
<label for="inputImage">Image</label>
<%= f.file_field :image, placeholder:"Image",accept:"image/*" %>
<%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
 <p><%= link_to "プロフィール編集", edit_user_path(current_user)%></p>
<% @users.each do |user| %>
<div>
  <p>name<%= user.name %></p>
  <p>image</p>
  <% if user.image.attached? %>
    <%= image_tag user.image, size: "200x200" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %>
  
</div>
<% end %>

app/views/users/show.html.erb
<% @users.each do |user| %>
<div>
  <p>image<%= image_tag @user.get_profile_image(100,100) %></p>
  <p>name<%= @user.name %></p>
</div>